const { ObjectId } = require("mongodb");

const fs = require("fs");

 

const { getDB } = require("../config/db");

 

const {

  findBestIndicator

} = require("../services/vectorSearchService");

 

const {

  generateFileHash

} = require("../services/fileHashService");

 

const {

  extractTextFromPDF

} = require("../services/pdfTextService");

 

const {

  extractTextFromImages

} = require("../services/ocrService");

 

const {

  verifyImageEvidenceFiles

} = require("../services/evidenceVerificationService");

 

const {

  verifyEvidenceText

} = require("../services/evidenceSemanticService");

 

const {

  verifyImageGeoLocation

} = require(

  "../services/geoVerificationService"

);

 

const {

  detectAIImage

} = require(

  "../services/aiImageDetectionService"

);

 

const {

  calculateOverallVerification

} = require(

  "../services/overallVerificationService"

);

 

 

 

function getBaseUrl(req) {

  const configuredUrl = process.env.PUBLIC_BACKEND_URL?.trim();

 

  if (configuredUrl) {

    return configuredUrl.replace(/\/+$/, "");

  }

 

  const forwardedProtocol = req.get("x-forwarded-proto");

  const forwardedHost = req.get("x-forwarded-host");

 

  const protocol = forwardedProtocol

    ? forwardedProtocol.split(",")[0].trim()

    : req.protocol;

 

  const host = forwardedHost

    ? forwardedHost.split(",")[0].trim()

    : req.get("host");

 

  return `${protocol}://${host}`.replace(/\/+$/, "");

}

 

function buildEvidenceUrl(req, filePath) {

  if (!filePath) return null;

 

  if (

    filePath.startsWith("http://") ||

    filePath.startsWith("https://")

  ) {

    return filePath;

  }

 

  const normalizedPath = filePath

    .replace(/\\/g, "/")

    .replace(/^\/+/, "");

 

  return `${getBaseUrl(req)}/${normalizedPath}`;

}

 

/*

 * Delete files that were uploaded to the server.

 *

 * Used when:

 * - validation fails

 * - duplicate files are detected

 * - indicator mapping fails

 * - an unexpected error occurs

 */

function removeUploadedFiles(files = []) {

  for (const file of files) {

    if (!file?.path) {

      continue;

    }

 

    fs.unlink(file.path, (error) => {

      if (error && error.code !== "ENOENT") {

        console.error(

          `Failed to remove uploaded file ${file.path}:`,

          error

        );

      }

    });

  }

}

 

/*

 * Remove page markers generated by pdf-parse.

 

 *

 * Example:

 * -- 1 of 2 --

 */

function cleanExtractedPDFText(text = "") {

  return String(text)

    .replace(

      /--\s*\d+\s+of\s+\d+\s*--/gi,

      ""

    )

    .replace(/\s+/g, " ")

    .trim();

}

 

/*

 * Validate whether a file is an image.

 */

function isImageFile(file) {

  return (

    file?.mimetype === "image/jpeg" ||

    file?.mimetype === "image/png"

  );

}

 

/*

 * Validate whether a file is a PDF.

 */

function isPDFFile(file) {

  return (

    file?.mimetype === "application/pdf"

  );

}

 

/*

 * Create a new activity.

 */

async function createActivity(req, res) {

  const uploadedFiles = req.files || [];

 

  try {

    const db = getDB();

 

    const activitiesCollection =

      db.collection("activities");

 

    const panchayatsCollection =

      db.collection("panchayats");

 

    const {

      villageCode,

      activity_text

    } = req.body;

 

    /*

     * Required-field validation.

     */

    if (!villageCode || !activity_text?.trim()) {

      removeUploadedFiles(uploadedFiles);

 

      return res.status(400).json({

        message:

          "villageCode and activity_text are required"

      });

    }

 

    const numericVillageCode =

      Number(villageCode);

 

    if (Number.isNaN(numericVillageCode)) {

      removeUploadedFiles(uploadedFiles);

 

      return res.status(400).json({

        message: "Invalid villageCode"

      });

    }

 

    /*

     * Role validation.

     */

    const allowedRoles = [

      "admin",

      "district_collector",

      "panchayat_official"

    ];

 

    if (

      !allowedRoles.includes(req.user.role)

    ) {

      removeUploadedFiles(uploadedFiles);

 

      return res.status(403).json({

        message: "Access denied"

      });

    }

 

    /*

     * Panchayat officials can add activities

     * only to their assigned panchayats.

     */

    if (

      req.user.role ===

      "panchayat_official"

    ) {

      const assignedPanchayats =

        req.user.assignedPanchayats || [];

 

      if (

        !assignedPanchayats.includes(

          numericVillageCode

        )

 

      ) {

        removeUploadedFiles(uploadedFiles);

 

        return res.status(403).json({

          message:

            "Access denied for this panchayat"

        });

      }

    }

 

    /*

     * Check whether the panchayat exists.

     */

    const panchayat =

      await panchayatsCollection.findOne({

        villageCode:

          numericVillageCode

      });

 

    if (!panchayat) {

      removeUploadedFiles(uploadedFiles);

 

      return res.status(404).json({

        message: "Panchayat not found"

      });

    }

 

    /*

     * Generate a SHA-256 hash for each file.

     *

     * This detects:

     * 1. Same file selected twice in one request.

     * 2. File previously uploaded for another activity.

     */

    const generatedHashes = [];

 

    for (const file of uploadedFiles) {

      const fileHash =

        await generateFileHash(file.path);

 

      /*

       * Duplicate inside the current request.

       */

      if (

        generatedHashes.includes(fileHash)

      ) {

        removeUploadedFiles(uploadedFiles);

 

        return res.status(409).json({

          message:

            "The same evidence file was selected more than once",

          duplicate: true

        });

      }

 

      /*

       * Duplicate already stored in MongoDB.

       */

      const duplicateEvidence =

        await activitiesCollection.findOne({

          "evidence.fileHash":

            fileHash

        });

 

      if (duplicateEvidence) {

        removeUploadedFiles(uploadedFiles);

 

        return res.status(409).json({

          message:

            `Evidence file "${file.originalname}" has already been uploaded`,

 

          duplicate: true,

 

          existingActivityId:

            duplicateEvidence._id

        });

      }

 

      generatedHashes.push(fileHash);

    }

 

    /*

     * Map the activity description

     * to an SDG indicator.

     */

    const matchedIndicator =

      await findBestIndicator(

        activity_text.trim()

      );

 

    if (!matchedIndicator) {

      removeUploadedFiles(uploadedFiles);

 

      return res.status(404).json({

        message:

          "No matching indicator found"

      });

    }

 

    /*

     * Get all uploaded image files.

     */

    const imageFiles =

      uploadedFiles.filter(isImageFile);

 

    /*

     * Detect whether each uploaded image is likely

     * to be AI-generated.

     */

    const aiImageDetectionResults =

      imageFiles.length > 0

        ? await Promise.all(

            imageFiles.map(async (file) => {

              const result =

                await detectAIImage(

                  file.path

                );

 

              return {

                filePath:

                  file.path,

 

                ...result

              };

            })

          )

        : [];

 

    /*

     * Convert AI-image detection results into a Map.

     *

     * Key: file.path

     * Value: AI-image detection result

     */

    const aiImageDetectionMap =

      new Map(

        aiImageDetectionResults.map(

          (result) => [

            result.filePath,

            result

          ]

        )

      );

 

    /*

     * Extract GPS metadata from every uploaded image

     * and compare it with the selected Panchayat's

     * reference coordinates.

     */

 

    const geoVerificationResults =

      imageFiles.length > 0

        ? await Promise.all(

            imageFiles.map(async (file) => {

              const result =

                await verifyImageGeoLocation({

                  filePath:

                    file.path,

 

                  panchayatGeoReference:

                    panchayat.geoReference

                });

 

              return {

                filePath:

                  file.path,

 

                ...result

              };

            })

          )

        : [];

 

    /*

     * Convert geo-verification results into a Map.

     *

     * Key:

     * file.path

     *

     * Value:

     * geo-verification result

     */

    const geoVerificationMap =

      new Map(

        geoVerificationResults.map(

          (result) => [

            result.filePath,

            result

          ]

        )

      );

 

    /*

     * Run OCR on all uploaded images.

     */

    const imageOCRResults =

      imageFiles.length > 0

        ? await extractTextFromImages(

            imageFiles

          )

        : [];

 

    /*

     * Convert OCR results into a Map.

     *

     * Key:

     * file.path

     *

     * Value:

     * OCR result

     */

    const imageOCRMap = new Map(

      imageOCRResults.map(

        (result) => [

          result.filePath,

          result

        ]

      )

    );

 

    /*

     * Send every uploaded image

     * to the OpenAI vision verifier.

     */

    const imageVerificationResults =

      imageFiles.length > 0

        ? await verifyImageEvidenceFiles({

            files: imageFiles,

 

            activityText:

              activity_text.trim(),

 

            indicatorCode:

              matchedIndicator

                .indicator_code,

 

            indicatorDescription:

              matchedIndicator

                .indicator_description,

 

            ocrResults:

              imageOCRMap

          })

        : [];

 

    /*

     * Convert vision results into a Map.

     */

    const imageVerificationMap =

      new Map(

        imageVerificationResults.map(

          (result) => [

            result.filePath,

            result

          ]

        )

      );

 

    /*

     * Process each uploaded evidence file.

 

     */

    const evidence = [];

 

    for (

      let index = 0;

      index < uploadedFiles.length;

      index++

    ) {

      const file =

        uploadedFiles[index];

 

      const isPDF =

        isPDFFile(file);

 

      const isImage =

        isImageFile(file);

 

      /*

       * Extraction fields.

       */

      let extractedText = "";

      let pageCount = null;

 

      let extractionStatus =

        "NOT_REQUIRED";

 

      let extractionError = null;

      let ocrConfidence = null;

 

      /*

       * Image vision-verification fields.

       */

      let verificationStatus =

        isImage

          ? "PENDING_ANALYSIS"

          : "NOT_APPLICABLE";

 

      let verificationScore = null;

      let verificationSummary = null;

 

      let visibleElements = [];

      let supportingReasons = [];

 

      let verificationLimitations = [];

 

      let suspectedActivity = null;

      let imageQuality = null;

      let verificationError = null;

 

      /*

       * AI-generated image detection fields.

       *

       * PDFs are marked NOT_APPLICABLE.

       */

      let aiImageDetection = {

        detectionStatus:

          isImage

            ? "NOT_ANALYSED"

            : "NOT_APPLICABLE",

 

        aiGeneratedProbability:

          null,

 

        confidence:

          null,

 

        provider:

          isImage

            ? "SIGHTENGINE"

            : null,

 

        reason:

          isImage

            ? "AI-image detection result was unavailable"

            : "AI-image detection is not applicable to PDF evidence",

 

        error:

          null

      };

 

      /*

       * Geo-tag verification fields.

       *

       * PDFs are marked NOT_APPLICABLE.

       * Images without GPS remain NOT_AVAILABLE.

       */

      let geoVerification = {

        metadataAvailable:

          false,

 

        imageLatitude:

          null,

 

        imageLongitude:

          null,

 

        capturedAt:

          null,

 

        panchayatLatitude:

          panchayat.geoReference

            ?.latitude ?? null,

 

        panchayatLongitude:

          panchayat.geoReference

            ?.longitude ?? null,

 

        distanceFromPanchayatKm:

          null,

 

        status:

          isImage

            ? "NOT_AVAILABLE"

            : "NOT_APPLICABLE",

 

        reason:

          isImage

            ? "The image does not contain usable GPS metadata"

            : "Geo-tag verification is not applicable to PDF evidence",

 

        error:

          null

      };

 

      /*

       * Extract selectable text from PDFs.

       */

      if (isPDF) {

        const pdfResult =

          await extractTextFromPDF(

            file.path

          );

 

        extractedText =

          cleanExtractedPDFText(

            pdfResult.text || ""

          );

 

        pageCount =

          pdfResult.pageCount ?? null;

 

        extractionError =

          pdfResult.extractionError ||

          null;

 

        if (extractionError) {

          extractionStatus = "FAILED";

        } else if (

          extractedText.length >= 10

        ) {

          extractionStatus =

            "COMPLETED";

        } else {

          /*

           * Usually means that the PDF

           * is scanned or image-based.

           */

          extractionStatus =

            "NO_TEXT_FOUND";

 

          extractedText = "";

        }

      }

 

      /*

       * Extract visible text from images

       * using Tesseract OCR.

       */

      if (isImage) {

        /*

         * Read the AI-image detection result

         * for this particular image.

         */

        const aiImageResult =

          aiImageDetectionMap.get(

            file.path

          );

 

        if (aiImageResult) {

          aiImageDetection = {

            detectionStatus:

              aiImageResult

                .detectionStatus ||

              "NOT_ANALYSED",

 

            aiGeneratedProbability:

              aiImageResult

                .aiGeneratedProbability ??

              null,

 

            confidence:

              aiImageResult.confidence ??

              null,

 

            provider:

              aiImageResult.provider ||

              "SIGHTENGINE",

 

            reason:

              aiImageResult.reason ||

              "AI-image detection result was unavailable",

 

            error:

              aiImageResult.error ||

              null

          };

        }

 

        /*

         * Read the geo-tag verification result

         * for this particular image.

         */

        const imageGeoResult =

          geoVerificationMap.get(

            file.path

          );

 

        if (imageGeoResult) {

          geoVerification = {

            metadataAvailable:

              imageGeoResult

                .metadataAvailable ??

              false,

 

            imageLatitude:

              imageGeoResult

                .imageLatitude ??

              null,

 

            imageLongitude:

              imageGeoResult

                .imageLongitude ??

              null,

 

            capturedAt:

              imageGeoResult

                .capturedAt ??

              null,

 

            panchayatLatitude:

              imageGeoResult

                .panchayatLatitude ??

              null,

 

            panchayatLongitude:

              imageGeoResult

                .panchayatLongitude ??

              null,

 

            distanceFromPanchayatKm:

              imageGeoResult

                .distanceFromPanchayatKm ??

              null,

 

            status:

              imageGeoResult.status ||

              "NOT_AVAILABLE",

 

            reason:

              imageGeoResult.reason ||

              "Geo-tag verification result was unavailable",

 

            error:

              imageGeoResult.error ||

              null

          };

        }

 

        const ocrResult =

          imageOCRMap.get(file.path);

 

        if (!ocrResult) {

          extractionStatus = "FAILED";

 

          extractionError =

            "OCR result was not available";

        } else {

          extractedText =

            String(

              ocrResult.text || ""

            ).trim();

 

          ocrConfidence =

            ocrResult.confidence ??

            null;

 

          extractionError =

            ocrResult.extractionError ||

            null;

 

          if (extractionError) {

            extractionStatus =

              "FAILED";

          } else if (

            extractedText.length >= 10 &&

            ocrConfidence !== null &&

            ocrConfidence >= 60

          ) {

            extractionStatus =

              "COMPLETED";

          } else if (

            extractedText.length > 0

          ) {

            extractionStatus =

              "LOW_CONFIDENCE";

          } else {

            extractionStatus =

              "NO_TEXT_FOUND";

          }

        }

 

        /*

         * Read the vision result

         * for this particular image.

         */

        const visionResult =

          imageVerificationMap.get(

            file.path

          );

 

        if (visionResult) {

          verificationStatus =

            visionResult.status ||

            "PENDING_ANALYSIS";

 

          verificationScore =

            visionResult.score ??

            null;

 

          verificationSummary =

            visionResult.summary ||

            null;

 

          visibleElements =

            Array.isArray(

              visionResult.visibleElements

            )

              ? visionResult

                  .visibleElements

              : [];

 

          supportingReasons =

            Array.isArray(

              visionResult

                .supportingReasons

            )

              ? visionResult

                  .supportingReasons

              : [];

 

          verificationLimitations =

            Array.isArray(

              visionResult.limitations

            )

              ? visionResult.limitations

              : [];

 

          suspectedActivity =

            visionResult

              .suspectedActivity ||

            null;

 

          imageQuality =

            visionResult.imageQuality ||

            null;

 

          verificationError =

            visionResult

              .verificationError ||

            null;

        }

      }

 

      /*

       * Perform semantic comparison between:

       *

       * - activity claim

       * - extracted PDF/OCR text

       *

       * Low-confidence OCR will be ignored

       * by the semantic service.

       */

      const textVerification =

        await verifyEvidenceText({

          activityText:

            activity_text.trim(),

 

          evidenceText:

            extractedText,

 

          indicatorCode:

            matchedIndicator

              .indicator_code,

 

          indicatorDescription:

            matchedIndicator

              .indicator_description,

 

          extractionStatus,

 

          ocrConfidence,

 

          fileType:

            isPDF

              ? "pdf"

              : "image"

        });

 

      /*

       * General evidence-processing reasons.

       */

      const verificationReasons = [

        "Evidence file passed duplicate checking"

      ];

 

      if (

        isPDF &&

        extractionStatus ===

          "COMPLETED"

      ) {

        verificationReasons.push(

          "Text was successfully extracted from the PDF"

        );

      }

 

      if (

        isPDF &&

        extractionStatus ===

          "NO_TEXT_FOUND"

      ) {

        verificationReasons.push(

          "No selectable text was found in the PDF"

        );

      }

 

      if (

        isImage &&

        extractionStatus ===

          "COMPLETED"

      ) {

        verificationReasons.push(

          "Text was successfully extracted from the image using OCR"

        );

      }

 

      if (

        isImage &&

        extractionStatus ===

          "LOW_CONFIDENCE"

      ) {

        verificationReasons.push(

          "OCR detected text, but its confidence was low"

        );

      }

 

      if (

        isImage &&

        extractionStatus ===

          "NO_TEXT_FOUND"

      ) {

        verificationReasons.push(

          "No readable text was found in the image"

        );

      }

 

      if (

        extractionStatus === "FAILED"

      ) {

        verificationReasons.push(

          "Text extraction failed"

        );

      }

 

      if (

        isImage &&

        verificationStatus !==

          "PENDING_ANALYSIS"

      ) {

        verificationReasons.push(

          "The image was analysed using AI vision verification"

        );

      }

 

      if (

        textVerification

          .textVerificationStatus ===

          "TEXT_SUPPORTED"

      ) {

        verificationReasons.push(

          "Extracted text strongly supports the activity claim"

        );

      }

 

      if (

        textVerification

          .textVerificationStatus ===

          "TEXT_PARTIALLY_SUPPORTED"

      ) {

        verificationReasons.push(

          "Extracted text partially supports the activity claim"

        );

      }

 

      if (

        textVerification

          .textVerificationStatus ===

          "TEXT_NOT_SUPPORTED"

      ) {

        verificationReasons.push(

          "Extracted text does not sufficiently support the activity claim"

 

        );

      }

 

      if (

        textVerification

          .textVerificationStatus ===

          "OCR_TOO_UNRELIABLE"

      ) {

        verificationReasons.push(

          "OCR confidence was too low for reliable semantic verification"

        );

      }

 

      /*

       * AI-image detection reasons.

       */

      if (

        isImage &&

        aiImageDetection

          .detectionStatus ===

          "LIKELY_REAL"

      ) {

        verificationReasons.push(

          "No strong AI-generation signal was detected in the image"

        );

      }

 

      if (

        isImage &&

        aiImageDetection

          .detectionStatus ===

          "SUSPICIOUS"

      ) {

        verificationReasons.push(

          "The image contains possible AI-generated patterns"

        );

      }

 

      if (

        isImage &&

        aiImageDetection

          .detectionStatus ===

          "LIKELY_AI_GENERATED"

      ) {

        verificationReasons.push(

          "The image was identified as likely AI-generated"

        );

      }

 

      if (

        isImage &&

        aiImageDetection

          .detectionStatus ===

          "ERROR"

      ) {

        verificationReasons.push(

          "AI-image detection could not be completed"

        );

      }

 

      /*

       * Geo-tag verification reasons.

       */

      if (

        isImage &&

        geoVerification.status ===

          "MATCHED"

      ) {

        verificationReasons.push(

          "The image GPS location matches the selected Panchayat"

        );

      }

 

      if (

        isImage &&

        geoVerification.status ===

          "NEARBY"

      ) {

        verificationReasons.push(

          "The image was captured near the selected Panchayat"

        );

      }

 

      if (

        isImage &&

        geoVerification.status ===

          "MISMATCHED"

      ) {

        verificationReasons.push(

          "The image GPS location does not match the selected Panchayat"

        );

      }

 

      if (

        isImage &&

        geoVerification.status ===

          "NOT_AVAILABLE"

      ) {

        verificationReasons.push(

          "The image does not contain usable GPS metadata"

        );

      }

 

      if (

        isImage &&

        geoVerification.status ===

          "PANCHAYAT_LOCATION_NOT_CONFIGURED"

      ) {

        verificationReasons.push(

          "Reference coordinates were unavailable for the selected Panchayat"

        );

      }

 

      if (

        isImage &&

        geoVerification.status ===

          "ERROR"

      ) {

        verificationReasons.push(

          "Geo-tag verification could not be completed"

        );

      }

 

      /*

       * Store complete evidence metadata.

       */

      evidence.push({

        originalName:

          file.originalname,

 

        storedName:

          file.filename,

 

        filePath:

          file.path.replace(

            /\\/g,

            "/"

          ),

 

        mimeType:

          file.mimetype,

 

        fileSize:

          file.size,

 

        fileType:

          isPDF

            ? "pdf"

            : "image",

 

        fileHash:

          generatedHashes[index],

 

        extractedText,

        pageCount,

 

        extractionStatus,

 

        extractionError,

 

        ocrConfidence,

 

        uploadedAt:

          new Date(),

 

        /*

         * Geo-tag verification.

         */

        geoVerification,

 

        /*

         * AI-generated image detection.

         */

        aiImageDetection,

 

        /*

         * Image-vision verification.

         */

        verificationStatus,

        verificationScore,

        verificationSummary,

 

        visibleElements,

        supportingReasons,

 

        verificationLimitations,

        suspectedActivity,

 

        imageQuality,

        verificationError,

 

        /*

         * Semantic text verification.

         */

        textVerificationStatus:

          textVerification

            .textVerificationStatus,

 

        textSimilarityScore:

          textVerification

            .textSimilarityScore,

 

        textSimilarityPercentage:

          textVerification

            .textSimilarityPercentage,

 

        textSupportsActivity:

          textVerification

            .textSupportsActivity,

 

        textVerificationReason:

          textVerification

            .textVerificationReason,

 

        textVerificationError:

          textVerification

            .textVerificationError ||

          null,

 

        verificationReasons

      });

    }

 

 

    const overallVerification =

        calculateOverallVerification(

            evidence

        );

 

 

 

    if (

  overallVerification.reviewStatus ===

  "REJECTED"

) {

  removeUploadedFiles(

    uploadedFiles

  );

 

  return res.status(422).json({

    message:

      "The uploaded evidence does not sufficiently support the activity. Please upload clearer or more relevant evidence.",

 

    overallVerificationScore:

      overallVerification

        .overallVerificationScore,

 

    overallVerificationStatus:

      overallVerification

        .overallVerificationStatus,

 

    reviewStatus:

      overallVerification

        .reviewStatus,

 

    overallVerificationSummary:

      overallVerification

        .overallVerificationSummary,

 

    reuploadRequired: true,

 

    evidence:

      evidence.map((item) => ({

        originalName:

          item.originalName,

 

        finalEvidenceScore:

          item.finalEvidenceScore,

 

        finalEvidenceStatus:

          item.finalEvidenceStatus,

 

        verificationScore:

 

          item.verificationScore,

 

        textSimilarityPercentage:

          item.textSimilarityPercentage,

 

        geoVerification:

          item.geoVerification,

 

        aiImageDetection:

          item.aiImageDetection

      }))

  });

  }

 

    /*

     * Create the final activity document.

     */

    const activityDoc = {

      villageCode:

        numericVillageCode,

 

      villageName:

        panchayat.villageName,

 

      districtName:

        panchayat.districtName,

 

      blockName:

        panchayat.blockName,

 

      activity_text:

        activity_text.trim(),

 

      status: "Completed",

 

      evidence,

 

 

      overallVerificationScore:

  overallVerification

    .overallVerificationScore,

 

overallVerificationStatus:

  overallVerification

    .overallVerificationStatus,

 

overallVerificationSummary:

  overallVerification

    .overallVerificationSummary,

 

reviewStatus:

  overallVerification

    .reviewStatus,

 

verifiedEvidenceCount:

  overallVerification

    .verifiedEvidenceCount,

 

flaggedEvidenceCount:

  overallVerification

    .flaggedEvidenceCount,

 

rejectedEvidenceCount:

  overallVerification

    .rejectedEvidenceCount,

 

totalEvidenceCount:

  overallVerification

    .totalEvidenceCount,

 

scoredEvidenceCount:

  overallVerification

    .scoredEvidenceCount,

 

collectorDecision:

  overallVerification.reviewStatus ===

  "FLAGGED_FOR_REVIEW"

    ? "PENDING"

    : null,

 

collectorRemarks: null,

reviewedBy: null,

reviewedAt: null,

 

      matched_indicator_code:

        matchedIndicator

          .indicator_code,

 

      matched_indicator_description:

        matchedIndicator

          .indicator_description,

 

      sdg_goal_number:

        matchedIndicator

          .sdg_goal_number,

 

      target_number:

        matchedIndicator

          .target_number,

 

      nodal_ministry:

        matchedIndicator

          .nodal_ministry,

 

      mapping_score:

        matchedIndicator.score,

 

      createdBy:

        req.user.username,

 

      createdByRole:

        req.user.role,

 

      createdAt:

        new Date(),

 

      updatedAt:

        new Date()

    };

 

    /*

     * Insert the activity into MongoDB.

     */

    const result =

      await activitiesCollection

        .insertOne(activityDoc);

 

    /*

     * Return the processed evidence details.

     */

    return res.status(201).json({

      message:

        "Activity recorded successfully",

 

      activityId:

        result.insertedId,

 

      evidenceCount:

        evidence.length,

 

      evidence:

        evidence.map(

          (item) => ({

            originalName:

              item.originalName,

 

            fileType:

              item.fileType,

 

            extractionStatus:

              item.extractionStatus,

 

            pageCount:

              item.pageCount,

 

            extractedTextLength:

              item.extractedText.length,

 

            ocrConfidence:

              item.ocrConfidence,

 

            /*

             * AI-image detection result.

             */

            aiImageDetection:

              item.aiImageDetection,

 

            /*

             * Geo-tag verification result.

             */

            geoVerification:

              item.geoVerification,

 

            /*

             * Vision result.

             */

            verificationStatus:

              item.verificationStatus,

 

            verificationScore:

              item.verificationScore,

 

            verificationSummary:

              item.verificationSummary,

 

            suspectedActivity:

              item.suspectedActivity,

 

            imageQuality:

              item.imageQuality,

 

            visibleElements:

              item.visibleElements,

 

            supportingReasons:

              item.supportingReasons,

 

            limitations:

              item

                .verificationLimitations,

 

            /*

             * Semantic text result.

             */

            textVerificationStatus:

              item

                .textVerificationStatus,

 

            textSimilarityScore:

              item

                .textSimilarityScore,

 

            textSimilarityPercentage:

              item

                .textSimilarityPercentage,

 

            textSupportsActivity:

              item

                .textSupportsActivity,

 

            textVerificationReason:

              item

                .textVerificationReason

          })

        ),

 

      mappedIndicator: {

        indicator_code:

          matchedIndicator

 

            .indicator_code,

 

        indicator_description:

          matchedIndicator

            .indicator_description,

 

        sdg_goal_number:

          matchedIndicator

            .sdg_goal_number,

 

        score:

          matchedIndicator.score

 

        

 

        

      },

 

      overallVerification: {

  score:

    overallVerification

      .overallVerificationScore,

 

  status:

    overallVerification

      .overallVerificationStatus,

 

  reviewStatus:

    overallVerification

      .reviewStatus,

 

  summary:

    overallVerification

      .overallVerificationSummary,

 

  verifiedEvidenceCount:

    overallVerification

      .verifiedEvidenceCount,

 

  totalEvidenceCount:

    overallVerification

      .totalEvidenceCount

},

    });

  } catch (error) {

    /*

     * Delete uploaded files when activity

     * creation fails unexpectedly.

     */

    removeUploadedFiles(uploadedFiles);

 

    console.error(

      "Error creating activity:",

      error

    );

 

    return res.status(500).json({

      message:

        "Server error while creating activity",

 

      error:

        process.env.NODE_ENV ===

        "development"

          ? error.message

          : undefined

    });

  }

}

 

/*

 * Get all activities for a village.

 */

async function getActivitiesByVillage(

  req,

  res

) {

  try {

    const db = getDB();

 

    const activitiesCollection =

      db.collection("activities");

 

    const villageCode =

      Number(

        req.params.villageCode

      );

 

    if (Number.isNaN(villageCode)) {

      return res.status(400).json({

        message:

          "Invalid village code"

      });

    }

 

    /*

     * Panchayat officials can access

     * only their assigned panchayats.

     */

    if (

      req.user.role ===

      "panchayat_official"

    ) {

      const assignedPanchayats =

        req.user.assignedPanchayats || [];

 

      if (

        !assignedPanchayats.includes(

          villageCode

        )

      ) {

 

        return res.status(403).json({

          message:

            "Access denied for this panchayat"

        });

      }

    }

 

   

 

 

  const activities =

  await activitiesCollection

    .find({

      villageCode

    })

    .sort({

      createdAt: -1

    })

    .toArray();

 

const formattedActivities =

  activities.map((activity) => ({

    ...activity,

 

    evidence: Array.isArray(activity.evidence)

      ? activity.evidence.map((item) => ({

          ...item,

 

          fileUrl: buildEvidenceUrl(

            req,

            item.filePath

          )

        }))

      : []

  }));

 

return res.status(200).json(

  formattedActivities

);

 

 

 

 

 

 

 

 

 

 

  } catch (error) {

    console.error(

      "Error fetching activities:",

      error

    );

 

    return res.status(500).json({

      message: "Server error"

    });

  }

}

 

/*

 * Delete an activity and its uploaded files.

 */

async function deleteActivity(

  req,

  res

) {

  try {

    const db = getDB();

 

    const activitiesCollection =

      db.collection("activities");

 

    const { activityId } =

      req.params;

 

    if (

      !ObjectId.isValid(activityId)

    ) {

      return res.status(400).json({

        message:

          "Invalid activityId"

      });

    }

 

    const existingActivity =

      await activitiesCollection.findOne({

        _id:

          new ObjectId(activityId)

      });

 

    if (!existingActivity) {

      return res.status(404).json({

        message:

          "Activity not found"

      });

    }

 

    const allowedRoles = [

      "admin",

      "district_collector",

      "panchayat_official"

    ];

 

    if (

      !allowedRoles.includes(req.user.role)

    ) {

      return res.status(403).json({

        message: "Access denied"

 

      });

    }

 

    /*

     * Panchayat access validation.

     */

    if (

      req.user.role ===

      "panchayat_official"

    ) {

      const assignedPanchayats =

        req.user.assignedPanchayats || [];

 

      if (

        !assignedPanchayats.includes(

          existingActivity.villageCode

        )

      ) {

        return res.status(403).json({

          message:

            "Access denied for this activity"

        });

      }

    }

 

    /*

     * Supports both:

     * - evidence arrays

     * - older single evidence objects

     */

    const evidenceFiles =

      Array.isArray(

        existingActivity.evidence

      )

        ? existingActivity.evidence

        : existingActivity.evidence

          ? [existingActivity.evidence]

          : [];

 

    /*

     * Delete physical files.

     */

    for (const evidenceItem of evidenceFiles) {

      if (!evidenceItem?.filePath) {

        continue;

      }

 

      fs.unlink(

        evidenceItem.filePath,

        (error) => {

          if (

            error &&

            error.code !== "ENOENT"

          ) {

            console.error(

              `Failed to delete evidence file ${evidenceItem.filePath}:`,

              error

            );

          }

        }

      );

    }

 

    /*

     * Delete MongoDB activity document.

     */

    await activitiesCollection.deleteOne({

      _id:

        new ObjectId(activityId)

    });

 

    return res.status(200).json({

      message:

        "Activity deleted successfully"

    });

  } catch (error) {

    console.error(

      "Error deleting activity:",

      error

    );

 

    return res.status(500).json({

      message:

        "Server error while deleting activity"

    });

  }

}

 

module.exports = {

  createActivity,

  getActivitiesByVillage,

  deleteActivity

};